spring:
  datasource:
    url: jdbc:mysql://www.another.ren:3306/cloudmusic?serverTimezone=UTC
    username: root
    password: AliCloud
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8989