spring:
  profiles:
    active: test
  servlet:
    multipart:
      # 最大文件大小
      max-file-size: 100MB
      # 最大请求大小
      max-request-size: 100MB
  jackson:
    #    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #    date-format: yyyy-MM-dd HH:mm:ss 2020-02-14 12:48:32
    #    date-format: java.text.SimpleDateFormat 20-2-14 上午12:48
    #    date-format: com.fasterxml.jackson.databind.util.StdDateFormat 2020-02-14T00:48:32.000+0800 默认值
    #    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat 2020-02-13T16:48:32Z
    #    date-format: javax.mail.internet.MailDateFormat Fri, 14 Feb 2020 00:48:32 +0800 (GMT+08:00)
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: star.sky.another